services:
  - type: web
    name: netguard-ids
    runtime: python
    plan: free
    healthCheckPath: /api/health/
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn netguard.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: MODEL_STARTUP_CHECK
        value: "False"
      - key: RF_API_URL
        value: "http://localhost:5000"
