# Generated by Django 5.2.1 on 2026-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('attack_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
