# Generated by Django 5.0.3 on 2026-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
